--INSERT INTO public.user values (-1, 'john', 0);
--INSERT INTO public.user values (-2, 'alex', 0);
--INSERT INTO public.user values (-3, 'nick', 0);
--INSERT INTO public.user values (-4, 'alan', 0);
--
--INSERT INTO public.customer values (1, 'Tony', '@tony.com', 'USA');
--INSERT INTO public.customer values (2, 'Hulk', '@hulk.com', 'USA');
--INSERT INTO public.customer values (3, 'IronMan', '@iron.com', 'USA');